on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Coredump Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Build gen_c
        run: gcc gen.c -o gen_c
      - name: Hello world action step
        #        uses: ./
        uses: dark-enstein/garn@master
        with:
          name: test.bf
      - name: Run segfault
        run: ./genc_c || true
      - name: List dir
        run: |
          set -euxo pipefail
          ls -all
          pwd
          df -h
      - name: check appport dir
        run: |
          ls -all /var/crash/
