on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Coredump Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        #        uses: ./
        uses: dark-enstein/garn@master
        with:
          name: test.bf
